### ISSUE TITLE
Include singular in gendered_symbols()

### ISSUE THREAD

**Issue by DominikVogel** [vivifabrien/gendered#2]
Hi Vivien,

great package. Thanks a lot! 

Is there a reason, why `gendered_symbols()` only captures plurals ("innen") but no singulars ("in")?

**Comment by vivifabrien** [comment]
Hi Dominik,
I developed this package for my thesis and for that I did not look into singular forms. 
But it definitely is something that should be added in the future.

**Comment by DominikVogel** [comment]
I see. Is there a theoretical reason for you not considering singular forms?

In case you want to implement it, I created a pull request that intends to add the feature by adding a `singular` parameter to `gendered_symbols()`.

https://github.com/vivifabrien/gendered/pull/3/commits/811fc50e493ec2e04d99a819d4e4c1597c3a001a

**Comment by vivifabrien** [comment]
Thank you! Appreciate it! Changes included in this merge: https://github.com/vivifabrien/gendered/pull/3
